<?php

namespace Database\Seeders;

use App\Modules\NewsRadar\Models\NewsSource;
use App\Modules\NewsRadar\Models\NewsTheme;
use Illuminate\Database\Seeder;

class NewsSourceSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedThemes();
        $this->seedSources();
    }

    private function seedThemes(): void
    {
        $themes = [
            'politica' => 'Política',
            'policia' => 'Polícia',
            'esporte' => 'Esporte',
            'economia' => 'Economia',
            'saude' => 'Saúde',
            'educacao' => 'Educação',
            'cultura' => 'Cultura',
            'tecnologia' => 'Tecnologia',
            'meio_ambiente' => 'Meio Ambiente',
            'transporte' => 'Transporte',
            'sociedade' => 'Sociedade',
            'internacional' => 'Internacional',
            'outro' => 'Outro',
        ];

        foreach ($themes as $slug => $label) {
            NewsTheme::firstOrCreate(['slug' => $slug], ['label' => $label]);
        }
    }

    private function seedSources(): void
    {
        $sources = $this->getSources();

        foreach ($sources as $data) {
            NewsSource::firstOrCreate(
                ['homepage_url' => $data['homepage_url']],
                $data,
            );
        }
    }

    private function getSources(): array
    {
        return [
            // ===== ESTADUAL / GRANDE PORTE =====
            [
                'name' => 'ND Mais',
                'homepage_url' => 'https://ndmais.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'feed',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Estadual',
                'crawling_config' => [
                    'feed_url' => 'https://ndmais.com.br/feed/',
                    'article_url_patterns' => ['/noticias/', '/esportes/', '/economia/'],
                    'ignore_url_patterns' => ['/colunistas/', '/horoscopo/'],
                ],
                'throttle_config' => ['crawl_interval_min' => 15, 'crawl_interval_max' => 45],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'NSC Total',
                'homepage_url' => 'https://www.nsctotal.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'feed',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Estadual',
                'crawling_config' => [
                    'feed_url' => 'https://www.nsctotal.com.br/feed',
                    'article_url_patterns' => ['/noticias/'],
                ],
                'throttle_config' => ['crawl_interval_min' => 15, 'crawl_interval_max' => 45],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'G1 Santa Catarina',
                'homepage_url' => 'https://g1.globo.com/sc/santa-catarina',
                'source_type' => 'portal',
                'discovery_mode' => 'feed',
                'feed_quality_profile' => 'full',
                'fetch_detail_mode' => 'never',
                'region' => 'Estadual',
                'crawling_config' => [
                    'feed_url' => 'https://g1.globo.com/rss/g1/sc/santa-catarina/',
                    'article_url_patterns' => ['/noticia/'],
                ],
                'throttle_config' => ['crawl_interval_min' => 15, 'crawl_interval_max' => 45],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'SCC10',
                'homepage_url' => 'https://sfranciscoonline.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Estadual',
                'crawling_config' => [
                    'feed_url' => 'https://sfranciscoonline.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 15, 'crawl_interval_max' => 60],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Diário Catarinense',
                'homepage_url' => 'https://www.nsctotal.com.br/noticias/diario-catarinense',
                'source_type' => 'portal',
                'discovery_mode' => 'html_listing',
                'feed_quality_profile' => 'teaser_only',
                'fetch_detail_mode' => 'always',
                'region' => 'Estadual',
                'crawling_config' => [
                    'listing_urls' => ['https://www.nsctotal.com.br/noticias/diario-catarinense'],
                    'selectors' => [
                        'item' => 'article, .news-item, .card',
                        'title' => 'h2 a, h3 a, .title a',
                        'link' => 'h2 a, h3 a, .title a',
                        'image' => 'img',
                    ],
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Correio do Povo SC',
                'homepage_url' => 'https://www.correiodopovo.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Estadual',
                'crawling_config' => [
                    'feed_url' => 'https://www.correiodopovo.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'OCP News',
                'homepage_url' => 'https://ocp.news',
                'source_type' => 'portal',
                'discovery_mode' => 'feed',
                'feed_quality_profile' => 'full',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Estadual',
                'crawling_config' => [
                    'feed_url' => 'https://ocp.news/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 20, 'crawl_interval_max' => 60],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Portal Ric SC',
                'homepage_url' => 'https://ric.com.br/sc',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Estadual',
                'crawling_config' => [
                    'feed_url' => 'https://ric.com.br/sc/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 20, 'crawl_interval_max' => 60],
                'active' => true,
                'consecutive_failures' => 0,
            ],

            // ===== GRANDE FLORIANÓPOLIS =====
            [
                'name' => 'Floripa News',
                'homepage_url' => 'https://floripanews.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Grande Florianópolis',
                'crawling_config' => [
                    'feed_url' => 'https://floripanews.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Click RBS Florianópolis',
                'homepage_url' => 'https://gauchazh.clicrbs.com.br/ultimas-noticias/tag/florianopolis/',
                'source_type' => 'portal',
                'discovery_mode' => 'html_listing',
                'feed_quality_profile' => 'teaser_only',
                'fetch_detail_mode' => 'always',
                'region' => 'Grande Florianópolis',
                'crawling_config' => [
                    'listing_urls' => ['https://gauchazh.clicrbs.com.br/ultimas-noticias/tag/florianopolis/'],
                    'selectors' => [
                        'item' => 'article, .news-card',
                        'title' => 'h2 a, h3 a',
                        'link' => 'h2 a, h3 a',
                        'image' => 'img',
                    ],
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'ND Mais Florianópolis',
                'homepage_url' => 'https://ndmais.com.br/cidade/florianopolis/',
                'source_type' => 'portal',
                'discovery_mode' => 'html_listing',
                'feed_quality_profile' => 'teaser_only',
                'fetch_detail_mode' => 'always',
                'region' => 'Grande Florianópolis',
                'crawling_config' => [
                    'listing_urls' => ['https://ndmais.com.br/cidade/florianopolis/'],
                    'selectors' => [
                        'item' => 'article, .card-news',
                        'title' => 'h2 a, h3 a',
                        'link' => 'h2 a, h3 a',
                        'image' => 'img',
                    ],
                ],
                'throttle_config' => ['crawl_interval_min' => 20, 'crawl_interval_max' => 60],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Notícias do Dia Floripa',
                'homepage_url' => 'https://www.noticiasdeflora.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Grande Florianópolis',
                'crawling_config' => [
                    'feed_url' => 'https://www.noticiasdeflora.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Prefeitura de Florianópolis',
                'homepage_url' => 'https://www.pmf.sc.gov.br',
                'source_type' => 'prefeitura',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'always',
                'region' => 'Grande Florianópolis',
                'crawling_config' => [
                    'listing_urls' => ['https://www.pmf.sc.gov.br/noticias/'],
                    'selectors' => [
                        'item' => '.noticia, .news-item, article',
                        'title' => 'h2 a, h3 a, .titulo a',
                        'link' => 'h2 a, h3 a, .titulo a',
                    ],
                ],
                'throttle_config' => ['crawl_interval_min' => 60, 'crawl_interval_max' => 180],
                'active' => true,
                'consecutive_failures' => 0,
            ],

            // ===== NORTE CATARINENSE =====
            [
                'name' => 'A Notícia (Joinville)',
                'homepage_url' => 'https://www.nsctotal.com.br/noticias/a-noticia',
                'source_type' => 'portal',
                'discovery_mode' => 'html_listing',
                'feed_quality_profile' => 'teaser_only',
                'fetch_detail_mode' => 'always',
                'region' => 'Norte',
                'crawling_config' => [
                    'listing_urls' => ['https://www.nsctotal.com.br/noticias/a-noticia'],
                    'selectors' => [
                        'item' => 'article, .news-item, .card',
                        'title' => 'h2 a, h3 a',
                        'link' => 'h2 a, h3 a',
                        'image' => 'img',
                    ],
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Portal Joinville',
                'homepage_url' => 'https://www.portaldejoinville.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Norte',
                'crawling_config' => [
                    'feed_url' => 'https://www.portaldejoinville.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'São Francisco Online',
                'homepage_url' => 'https://sfranciscoonline.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Norte',
                'crawling_config' => [
                    'feed_url' => 'https://sfranciscoonline.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Jaraguá AM',
                'homepage_url' => 'https://www.jaraguaam.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Norte',
                'crawling_config' => [
                    'feed_url' => 'https://www.jaraguaam.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Mafra Online',
                'homepage_url' => 'https://www.mafraonline.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Norte',
                'crawling_config' => [
                    'feed_url' => 'https://www.mafraonline.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Rádio Jaraguá',
                'homepage_url' => 'https://www.radioaragua.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Norte',
                'crawling_config' => [
                    'feed_url' => 'https://www.radioaragua.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],

            // ===== VALE DO ITAJAÍ =====
            [
                'name' => 'O Município (Brusque)',
                'homepage_url' => 'https://omunicipio.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'feed',
                'feed_quality_profile' => 'full',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Vale do Itajaí',
                'crawling_config' => [
                    'feed_url' => 'https://omunicipio.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 20, 'crawl_interval_max' => 60],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Jornal de Santa Catarina',
                'homepage_url' => 'https://www.nsctotal.com.br/noticias/jornal-de-santa-catarina',
                'source_type' => 'portal',
                'discovery_mode' => 'html_listing',
                'feed_quality_profile' => 'teaser_only',
                'fetch_detail_mode' => 'always',
                'region' => 'Vale do Itajaí',
                'crawling_config' => [
                    'listing_urls' => ['https://www.nsctotal.com.br/noticias/jornal-de-santa-catarina'],
                    'selectors' => [
                        'item' => 'article, .card',
                        'title' => 'h2 a, h3 a',
                        'link' => 'h2 a, h3 a',
                        'image' => 'img',
                    ],
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Blumenau em Foco',
                'homepage_url' => 'https://www.blumenauemfoco.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Vale do Itajaí',
                'crawling_config' => [
                    'feed_url' => 'https://www.blumenauemfoco.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Revista News (Blumenau)',
                'homepage_url' => 'https://revistanews.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Vale do Itajaí',
                'crawling_config' => [
                    'feed_url' => 'https://revistanews.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Diarinho (Itajaí)',
                'homepage_url' => 'https://www.dfranciscoonline.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Vale do Itajaí',
                'crawling_config' => [
                    'feed_url' => 'https://www.dfranciscoonline.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Navegantes Online',
                'homepage_url' => 'https://www.navegantesonline.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Vale do Itajaí',
                'crawling_config' => [
                    'feed_url' => 'https://www.navegantesonline.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Balneário Camboriú News',
                'homepage_url' => 'https://www.bcnews.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Vale do Itajaí',
                'crawling_config' => [
                    'feed_url' => 'https://www.bcnews.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],

            // ===== LITORAL NORTE (Itajaí / BC / Camboriú) =====
            [
                'name' => 'Portal Costa Norte',
                'homepage_url' => 'https://www.portalcostanorte.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Litoral Norte',
                'crawling_config' => [
                    'feed_url' => 'https://www.portalcostanorte.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Diário do Litoral',
                'homepage_url' => 'https://www.diariodolitoral.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Litoral Norte',
                'crawling_config' => [
                    'feed_url' => 'https://www.diariodolitoral.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Camboriú News',
                'homepage_url' => 'https://www.camboriúnews.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Litoral Norte',
                'crawling_config' => [
                    'feed_url' => 'https://www.camboriúnews.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],

            // ===== SUL CATARINENSE =====
            [
                'name' => 'Engeplus (Criciúma)',
                'homepage_url' => 'https://www.engeplus.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'feed',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Sul',
                'crawling_config' => [
                    'feed_url' => 'https://www.engeplus.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Portal Veneza (Tubarão)',
                'homepage_url' => 'https://www.portalveneza.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Sul',
                'crawling_config' => [
                    'feed_url' => 'https://www.portalveneza.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Jornal da Manhã (Criciúma)',
                'homepage_url' => 'https://www.jornaldamanha.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Sul',
                'crawling_config' => [
                    'feed_url' => 'https://www.jornaldamanha.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => '4Oito (Criciúma)',
                'homepage_url' => 'https://www.4oito.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Sul',
                'crawling_config' => [
                    'feed_url' => 'https://www.4oito.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Sul in Foco',
                'homepage_url' => 'https://www.sulinfoco.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Sul',
                'crawling_config' => [
                    'feed_url' => 'https://www.sulinfoco.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Rádio Eldorado (Criciúma)',
                'homepage_url' => 'https://www.radioeldorado.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Sul',
                'crawling_config' => [
                    'feed_url' => 'https://www.radioeldorado.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Notisul (Tubarão)',
                'homepage_url' => 'https://www.notisul.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Sul',
                'crawling_config' => [
                    'feed_url' => 'https://www.notisul.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],

            // ===== OESTE CATARINENSE =====
            [
                'name' => 'Rádio Chapecó',
                'homepage_url' => 'https://www.radiochapeco.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Oeste',
                'crawling_config' => [
                    'feed_url' => 'https://www.radiochapeco.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Portal Chapecó',
                'homepage_url' => 'https://www.portalchapeco.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Oeste',
                'crawling_config' => [
                    'feed_url' => 'https://www.portalchapeco.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Oeste Mais',
                'homepage_url' => 'https://www.oestemais.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Oeste',
                'crawling_config' => [
                    'feed_url' => 'https://www.oestemais.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 90],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Folha do Oeste',
                'homepage_url' => 'https://www.folhadooeste.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Oeste',
                'crawling_config' => [
                    'feed_url' => 'https://www.folhadooeste.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Rádio Índio Condá',
                'homepage_url' => 'https://www.radioindio.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Oeste',
                'crawling_config' => [
                    'feed_url' => 'https://www.radioindio.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Xanxerê Online',
                'homepage_url' => 'https://www.xanxereonline.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Oeste',
                'crawling_config' => [
                    'feed_url' => 'https://www.xanxereonline.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Concórdia Online',
                'homepage_url' => 'https://www.concordiaonline.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Oeste',
                'crawling_config' => [
                    'feed_url' => 'https://www.concordiaonline.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],

            // ===== SERRA CATARINENSE =====
            [
                'name' => 'Serra SC',
                'homepage_url' => 'https://www.serrasc.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Serra',
                'crawling_config' => [
                    'feed_url' => 'https://www.serrasc.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Lages Diário',
                'homepage_url' => 'https://www.lagesdiario.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Serra',
                'crawling_config' => [
                    'feed_url' => 'https://www.lagesdiario.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Rádio Club (Lages)',
                'homepage_url' => 'https://www.radioclublages.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Serra',
                'crawling_config' => [
                    'feed_url' => 'https://www.radioclublages.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Portal São Joaquim Online',
                'homepage_url' => 'https://www.saojoaquimonline.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Serra',
                'crawling_config' => [
                    'feed_url' => 'https://www.saojoaquimonline.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 60, 'crawl_interval_max' => 180],
                'active' => true,
                'consecutive_failures' => 0,
            ],

            // ===== MEIO-OESTE =====
            [
                'name' => 'Rádio Videira',
                'homepage_url' => 'https://www.radiovideira.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Meio-Oeste',
                'crawling_config' => [
                    'feed_url' => 'https://www.radiovideira.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Joaçaba Online',
                'homepage_url' => 'https://www.joacabaonline.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Meio-Oeste',
                'crawling_config' => [
                    'feed_url' => 'https://www.joacabaonline.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],

            // ===== PLANALTO NORTE =====
            [
                'name' => 'Canoinhas Online',
                'homepage_url' => 'https://www.canoinhas.net',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Planalto Norte',
                'crawling_config' => [
                    'feed_url' => 'https://www.canoinhas.net/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Rio Negrinho Online',
                'homepage_url' => 'https://www.rionegrinhoonline.com.br',
                'source_type' => 'portal',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Planalto Norte',
                'crawling_config' => [
                    'feed_url' => 'https://www.rionegrinhoonline.com.br/feed/',
                ],
                'throttle_config' => ['crawl_interval_min' => 30, 'crawl_interval_max' => 120],
                'active' => true,
                'consecutive_failures' => 0,
            ],

            // ===== AGÊNCIAS / GOVERNO =====
            [
                'name' => 'Governo de SC',
                'homepage_url' => 'https://www.sc.gov.br',
                'source_type' => 'agencia',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'full',
                'fetch_detail_mode' => 'when_incomplete',
                'region' => 'Estadual',
                'crawling_config' => [
                    'feed_url' => 'https://www.sc.gov.br/index.php/noticias?format=feed&type=rss',
                    'listing_urls' => ['https://www.sc.gov.br/noticias'],
                    'selectors' => [
                        'item' => 'article, .item-page',
                        'title' => 'h2 a, .page-header a',
                        'link' => 'h2 a, .page-header a',
                    ],
                ],
                'throttle_config' => ['crawl_interval_min' => 60, 'crawl_interval_max' => 180],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'ALESC (Assembleia Legislativa)',
                'homepage_url' => 'https://www.alesc.sc.gov.br',
                'source_type' => 'agencia',
                'discovery_mode' => 'html_listing',
                'feed_quality_profile' => 'teaser_only',
                'fetch_detail_mode' => 'always',
                'region' => 'Estadual',
                'crawling_config' => [
                    'listing_urls' => ['https://www.alesc.sc.gov.br/noticias'],
                    'selectors' => [
                        'item' => '.views-row, article',
                        'title' => 'h2 a, .title a',
                        'link' => 'h2 a, .title a',
                    ],
                ],
                'throttle_config' => ['crawl_interval_min' => 60, 'crawl_interval_max' => 240],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Tribunal de Justiça de SC',
                'homepage_url' => 'https://www.tjsc.jus.br',
                'source_type' => 'agencia',
                'discovery_mode' => 'html_listing',
                'feed_quality_profile' => 'teaser_only',
                'fetch_detail_mode' => 'always',
                'region' => 'Estadual',
                'crawling_config' => [
                    'listing_urls' => ['https://www.tjsc.jus.br/web/home/-/noticias'],
                    'selectors' => [
                        'item' => '.asset-list-item, article',
                        'title' => 'h3 a, .title a',
                        'link' => 'h3 a, .title a',
                    ],
                ],
                'throttle_config' => ['crawl_interval_min' => 60, 'crawl_interval_max' => 240],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Ministério Público de SC',
                'homepage_url' => 'https://www.mpsc.mp.br',
                'source_type' => 'agencia',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'always',
                'region' => 'Estadual',
                'crawling_config' => [
                    'listing_urls' => ['https://www.mpsc.mp.br/noticias'],
                    'selectors' => [
                        'item' => '.noticia, article',
                        'title' => 'h2 a, h3 a',
                        'link' => 'h2 a, h3 a',
                    ],
                ],
                'throttle_config' => ['crawl_interval_min' => 60, 'crawl_interval_max' => 240],
                'active' => true,
                'consecutive_failures' => 0,
            ],
            [
                'name' => 'Defesa Civil de SC',
                'homepage_url' => 'https://www.defesacivil.sc.gov.br',
                'source_type' => 'agencia',
                'discovery_mode' => 'auto',
                'feed_quality_profile' => 'partial',
                'fetch_detail_mode' => 'always',
                'region' => 'Estadual',
                'crawling_config' => [
                    'listing_urls' => ['https://www.defesacivil.sc.gov.br/noticias/'],
                ],
                'throttle_config' => ['crawl_interval_min' => 60, 'crawl_interval_max' => 240],
                'active' => true,
                'consecutive_failures' => 0,
            ],
        ];
    }
}
